#!/bin/bash

set -e

if [[ -z $DOCKER_REPO && -n $1 ]]; then
  DOCKER_REPO=$1
fi

if [[ -z $DOCKER_REPO ]]; then
  echo '!!! Please set DOCKER_REPO or pass in repo URL on command line'
  exit 1
fi

echo '--- pulling latest base image'
docker pull $(grep '^FROM' $(dirname "$0")/Dockerfile | awk '{print $2}')

echo '--- building docker image'
if [[ -z $BUILDBOX_BRANCH ]]; then
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
  BRANCH=$BUILDBOX_BRANCH
fi

if [[ -z $BUILDBOX_COMMIT ]]; then
  COMMIT=HEAD
else
  COMMIT=$BUILDBOX_COMMIT
fi

IMAGE_TAG=${BRANCH}-$(git rev-parse --short ${COMMIT})

docker build -t $DOCKER_REPO:$IMAGE_TAG $(dirname $0)

if [[ $CI = "true" && $BUILDBOX_PULL_REQUEST = "false" ]]; then
  echo '--- pushing docker image to registry'
  docker push $DOCKER_REPO
else
  echo "If you'd like to push this to the Docker repo, run: docker push ${DOCKER_REPO}:${IMAGE_TAG}"
fi

echo '--- saving docker image tag'
if hash buildbox-agent 2>/dev/null ; then
  buildbox-agent build-data set docker-image "${DOCKER_REPO}:${IMAGE_TAG}"
fi
