#!/bin/bash

set -e

function usage() {
  echo -e "Usage:\n\ndeploy docker_image\n\nEx: deploy quay.io/democracyworks/buildkite-agent:docker"
}

echo '--- retrieving repo and tag'
if [[ -z $DOCKER_IMAGE ]]; then
  if [[ -n $1 ]]; then
    DOCKER_IMAGE=$1
  elif hash buildbox-agent 2>/dev/null; then
    DOCKER_IMAGE=$(buildbox-agent build-data get docker-image)
  fi
fi

if [[ -z $DOCKER_IMAGE ]]; then
  usage
  exit 1
fi

IMAGE_TAG=$(echo $DOCKER_IMAGE | awk -F: '{print $2}')

echo '--- updating fleet service template'
perl -p -i -e "s/^Environment=VERSION=.+$/Environment=VERSION=${IMAGE_TAG}/" buildkite@.service
if [[ $CI = "true" ]]; then
  fleetctl="docker run --net=host --rm cap10morgan/fleetctl:0.9.1"
else
  fleetctl="fleetctl"
fi

$fleetctl destroy buildkite@.service
$fleetctl submit buildkite@.service

echo '--- (re-)starting fleet service instances'
for i in {1..3}; do
  $fleetctl destroy buildkite@$i
  $fleetctl start buildkite@$i
done
