#!/bin/bash

set -e

if [[ -n "${GITHUB_PRIVATE_KEY}" ]]; then
  echo "${GITHUB_PRIVATE_KEY}" > /root/.ssh/id_rsa
  chmod 600 /root/.ssh/id_rsa
fi

if [[ -n "${DOCKERCFG}" ]]; then
  echo "${DOCKERCFG}" > /root/.dockercfg
fi

exec buildkite-agent $@
